from __future__ import annotations
from pathlib import Path
from typing import Dict, Any
from .base import BaseArchitect


class ArchitectAgent(BaseArchitect):
    """
    Architect Agent (skeleton).

    Takes a merged_plan from the Planner Council and produces:
      - docs/ARCHITECTURE.md
      - ops/PHASES.md

    Future versions will use LLMs to generate richer documents.
    """

    def __init__(self) -> None:
        pass

    # -----------------------------
    # Markdown generation
    # -----------------------------

    def generate_architecture_overview(self, merged_plan: Dict[str, Any]) -> str:
        """
        Produce a stub Markdown architecture overview.
        """
        phases = merged_plan.get("phases", [])
        notes = merged_plan.get("notes", [])
        lines: list[str] = [
            "# Architecture Overview (Stub)",
            "",
            "This is a skeleton architecture overview generated by ArchitectAgent.",
            "",
            "## Phases",
        ]
        for idx, ph in enumerate(phases, start=1):
            lines.append(f"- Phase {idx}: {ph}")
        lines.append("")
        lines.append("## Notes")
        for n in notes:
            lines.append(f"- {n}")
        lines.append("")
        return "\n".join(lines)

    def generate_phases_outline(self, merged_plan: Dict[str, Any]) -> str:
        """
        Produce a simple outline of phases with placeholder content.
        """
        phases = merged_plan.get("phases", [])
        lines: list[str] = ["# Phases Outline (Stub)", ""]
        for idx, ph in enumerate(phases, start=1):
            lines.append(f"## Phase {idx}: {ph}")
            lines.append("")
            lines.append("- TODO: Expand tasks for this phase")
            lines.append("")
        return "\n".join(lines)

    # -----------------------------
    # Document builders
    # -----------------------------

    def build_documents(self, merged_plan: Dict[str, Any]) -> Dict[str, str]:
        """
        Return in-memory strings for ARCHITECTURE.md and PHASES.md.
        """
        return {
            "architecture_md": self.generate_architecture_overview(merged_plan),
            "phases_md": self.generate_phases_outline(merged_plan),
        }

    def write_documents(self, merged_plan: Dict[str, Any]) -> None:
        """
        Write ARCHITECTURE.md and PHASES.md to disk.
        Creates docs/ and ops/ if they do not exist.
        """
        docs = self.build_documents(merged_plan)

        docs_dir = Path("docs")
        docs_dir.mkdir(parents=True, exist_ok=True)
        (docs_dir / "ARCHITECTURE.md").write_text(docs["architecture_md"], encoding="utf-8")

        ops_dir = Path("ops")
        ops_dir.mkdir(parents=True, exist_ok=True)
        (ops_dir / "PHASES.md").write_text(docs["phases_md"], encoding="utf-8")
