"""
Backend Specialist Agent.
"""
from datetime import datetime
from .base import SpecialistBase


class BackendSpecialist(SpecialistBase):
    """
    Backend specialist handles API design, database schema,
    and server-side architecture.
    """

    def __init__(self):
        """Initialize the Backend specialist."""
        super().__init__("backend")

    def generate_output(self) -> str:
        """
        Generate backend specialist report.

        Returns:
            Formatted backend analysis report
        """
        timestamp = datetime.now().isoformat()

        content = f"""Backend Specialist Report
=========================

This is generated by the backend specialist.
Timestamp: {timestamp}

## Analysis Summary

The backend specialist has analyzed the project structure and identified
the following areas for backend development:

### API Design
- RESTful API endpoints
- Request/response schemas
- Authentication and authorization

### Database Architecture
- Schema design
- Data models
- Migration strategy

### Server Infrastructure
- Application server configuration
- Caching strategy
- Background job processing

### Recommendations
1. Implement proper error handling
2. Add comprehensive logging
3. Set up monitoring and alerting
4. Optimize database queries
5. Implement rate limiting

---
Generated by CodeCompanion Backend Specialist
"""
        return content
