name: ci
# on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -m pip install -U pip uv
      - run: uv pip install -r requirements.txt || pip install -r requirements.txt
      - run: ruff format --check .
      - run: ruff check .
      - run: pyright || true
      - run: pytest -q --maxfail=1 --disable-warnings --cov --cov-report=term-missing